### ISSUE TITLE
Comparisons and References between SVDLibC and PROPACK

### ISSUE THREAD

**Issue by BradKML** [piskvorky/sparsesvd#11]
There has been documentation claiming that SVDLibC is fast in certain cases, and Propack in others.
https://jakevdp.github.io/blog/2012/12/19/sparse-svds-in-python/

It seems that Propack is in the archive as seen in https://github.com/jakevdp/pypropack

Would it be good to give pointers to other fast SVD libraries?

**Comment by BradKML** [comment]
Also as an idiot who read http://www.lrec-conf.org/proceedings/lrec2018/pdf/247.pdf
but also realizes that the method using SVD of a PPMI grid is not included in Gensim:
https://radimrehurek.com/gensim/models/lsimodel.html
And it only has NMF and not SVD proper: https://radimrehurek.com/gensim/models/nmf.html

**Comment by piskvorky** [comment]
Sorry, I don't understand either of your comments.

> Would it be good to give pointers to other fast SVD libraries?

This package is for SVDLIBC.

> And it only has NMF and not SVD proper

Gensim implements both fast (and sparse) SVD and NMF.

**Comment by BradKML** [comment]
@piskvorky okay, to rephrase what I said, are there any references to alternate SVD algorithms that are either faster or more popular than SVDLibC?

> Gensim implements both fast (and sparse) SVD and NMF.

Here is a reference to Gensim that has SVD (in the form of LSI/LSA):
https://radimrehurek.com/gensim/models/lsimodel.html

Question: Can one input a non-TF-IDF matrix into this (a spare-like matrix with PPMI mind you), and expect it to work?

**Comment by piskvorky** [comment]
>  are there any references to alternate SVD algorithms that are either faster or more popular than SVDLibC?

Yes – the one in Gensim, for example :) It's called "streamed stochastic truncated SVD", see the references in the Gensim docs.

> Can one input a non-TF-IDF matrix into this (a spare-like matrix with PPMI mind you), and expect it to work?

Gensim accepts arbitrary streamed matrices. See the `corpus` parameter of [gensim.models.lsimodel.LsiModel()](https://radimrehurek.com/gensim/models/lsimodel.html#gensim.models.lsimodel.LsiModel) or [gensim.models.lsimodel.stochastic_svd](https://radimrehurek.com/gensim/models/lsimodel.html#gensim.models.lsimodel.stochastic_svd).

**Comment by BradKML** [comment]
Ahhh this is where the other implementations were:
- LAPACK/ARPACK https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html
- ARPACK https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html

**Comment by BradKML** [comment]
Currently testing with stochastic_svd instead, as the main LSI model is not working
