### ISSUE TITLE
TypeError, but matrix seems declared correctly

### ISSUE THREAD

**Issue by iholas** [piskvorky/sparsesvd#7]
I have a sparse matrix M when I run `type(M)`, I get

`scipy.sparse.csr.csr_matrix`

However, when I use the matrix in sparesvd function as

`K = 60 `
`U, S, Vt = sparsesvd(M, K)`
I get an error:

`TypeError: First argument must be a scipy.sparse.csc_matrix`

Are those two not the same types?

**Comment by menshikh-iv** [comment]
Hello @iholas,

you have cs**r** matrix, but cs**c** needed

**Comment by iholas** [comment]
Thank you -- my dyslexia reared its ugly head. 

Thanks again.
